
spring:
  application:
    name: "TestSenderEmail"

  mail:
    host: "smtp.yandex.ru"
    port: "587"
    username:
    password:
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"
