#spring.application.name=TestSenderEmail
#
#spring.mail.host=smtp.yandex.ru
#spring.mail.port=587
#spring.mail.username=shinckov@yandex.ru
#spring.mail.password=cwtrtdawporvurzp
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring:
  application:
    name: "TestSenderEmail"

  mail:
    host: "smtp.yandex.ru"
    port: "587"
    username:
    password:
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"